In [46]:
import numpy as np
import torch

In [47]:
torch.__version__

'1.12.1'

In [50]:
arr = np.array([1,2,5,3,6])

In [51]:
print(arr)

[1 2 5 3 6]


In [52]:
arr.dtype

dtype('int64')

In [53]:
type(arr)

numpy.ndarray

In [54]:
x =torch.from_numpy(arr)

In [55]:
type(x)

torch.Tensor

In [56]:
torch.as_tensor(arr)

tensor([1, 2, 5, 3, 6])

In [57]:
x.dtype

torch.int64

In [58]:
arr2d = np.arange(0.0,12.0)

In [59]:
arr2d = arr2d.reshape(4,3)

In [60]:
x2 = torch.from_numpy(arr2d)

In [61]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [62]:
arr[0] = 99

In [63]:
x

tensor([99,  2,  5,  3,  6])

In [64]:
my_arr = np.arange(0,10)

In [65]:
my_tensor = torch.tensor(my_arr)

In [66]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
my_other_tensor = torch.from_numpy(my_arr)

In [68]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
my_arr[1] = 99999

In [70]:
my_other_tensor

tensor([    0, 99999,     2,     3,     4,     5,     6,     7,     8,     9])

In [71]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
new_arr = np.array([12,333,44])

In [73]:
new_arr.dtype

dtype('int64')

In [78]:
j = torch.tensor(new_arr)

In [79]:
j.dtype

torch.int64

In [80]:
h = torch.Tensor(new_arr)

In [81]:
h.dtype

torch.float32

In [82]:
torch.empty(2,2)

tensor([[0.0000e+00, 0.0000e+00],
        [8.2652e-10, 3.4007e-06]])

In [85]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [86]:
torch.linspace(0,18,12)

tensor([ 0.0000,  1.6364,  3.2727,  4.9091,  6.5455,  8.1818,  9.8182, 11.4545,
        13.0909, 14.7273, 16.3636, 18.0000])

In [89]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [92]:
ch_type = torch.tensor([[1,2,3],[3,4,3],[6,5,6]])

In [93]:
ch_type.dtype

torch.int64

In [95]:
ch_type = ch_type.type(torch.int32)

In [96]:
ch_type

tensor([[1, 2, 3],
        [3, 4, 3],
        [6, 5, 6]], dtype=torch.int32)

In [97]:
torch.rand(4,3)

tensor([[0.3049, 0.3101, 0.5988],
        [0.7516, 0.1911, 0.4859],
        [0.0215, 0.6229, 0.1872],
        [0.0865, 0.0919, 0.1646]])

In [98]:
torch.randn(4,3)

tensor([[ 0.7247,  0.3300,  1.1987],
        [-1.7648,  0.8586,  0.5190],
        [-0.3820, -0.4252,  0.9224],
        [ 0.2409, -0.2437, -1.0265]])

In [100]:
torch.randint(low=0,high=10,size = (5,5))

tensor([[4, 5, 0, 6, 5],
        [1, 8, 9, 7, 9],
        [9, 2, 1, 7, 3],
        [5, 7, 3, 2, 4],
        [1, 9, 7, 3, 7]])

In [101]:
x = torch.zeros(2,5) 

In [102]:
x


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [103]:
x.shape

torch.Size([2, 5])

In [104]:
torch.rand_like(x)

tensor([[0.5141, 0.4218, 0.8623, 0.9073, 0.5185],
        [0.7241, 0.3200, 0.8559, 0.4045, 0.0809]])

In [105]:
torch.randint_like(x,low=0,high=20)

tensor([[17.,  4.,  3., 12.,  5.],
        [19., 19., 11., 14.,  4.]])

In [109]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [111]:
x = torch.arange(6).reshape(3,2)

In [119]:
x[:,1]

tensor([1, 3, 5])

In [135]:
y = torch.arange(20)

In [136]:
len(y)

20

In [139]:
y.view(4,5)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [145]:
y = y.view(-1,5)

In [146]:
y.shape

torch.Size([4, 5])

In [147]:
a = torch.tensor([1.,2.,3.])

In [149]:
b = torch.tensor([4.,5.,6.])

In [150]:
a + b

tensor([5., 7., 9.])

In [153]:
b.dot(a) 

tensor(32.)

In [154]:
a @ b

tensor(32.)

In [155]:
a.norm()

tensor(3.7417)

In [156]:
x.numel()

6

In [157]:
len(x)

3